package com.ironscape.travel;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.List;
import net.runelite.api.coords.WorldPoint;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * The travel table is generated by tools/build-travel-distances.mjs from a
 * list of landings that lives in TWO other places — minigame_landings.json and
 * the TELEPORT_SPELLS / SPIRIT_TREES constants in IronscapePlugin. Nothing at
 * runtime notices when those drift apart: a renamed landing simply answers
 * UNKNOWN and the hint quietly falls back to the straight lines this table
 * exists to replace. That is the failure the bundled-places test was written
 * for after a duplicate JSON key took every place link down with one swallowed
 * warning, so it gets the same treatment — fail the build, not the play session.
 */
public class TravelDistancesTest
{
	/** Mirrors TELEPORT_SPELLS in IronscapePlugin (name only; coordinates live there). */
	private static final List<String> SPELLS = Arrays.asList(
		"Varrock Teleport", "Lumbridge Teleport", "Falador Teleport",
		"Camelot Teleport", "Ardougne Teleport", "Watchtower Teleport");

	/** Mirrors SPIRIT_TREE_ORIGINS in IronscapePlugin. */
	private static final List<String> TREES = Arrays.asList(
		"Spirit Tree: Tree Gnome Village", "Spirit Tree: Gnome Stronghold",
		"Spirit Tree: Battlefield of Khazard", "Spirit Tree: Grand Exchange",
		"Spirit Tree: Feldip Hills");

	@Test
	public void tableLoads()
	{
		assertTrue("travel_distances.bin.gz failed to load", new TravelDistances().isLoaded());
	}

	@Test
	public void everyLandingHasAField() throws Exception
	{
		TravelDistances travel = new TravelDistances();
		try (InputStream in = TravelDistances.class
			.getResourceAsStream("/com/ironscape/places/minigame_landings.json"))
		{
			assertNotNull("minigame_landings.json missing", in);
			JsonObject landings = new Gson().fromJson(
				new InputStreamReader(in, StandardCharsets.UTF_8), JsonObject.class)
				.getAsJsonObject("landings");
			for (String name : landings.keySet())
			{
				assertTrue("no travel field for minigame landing '" + name
					+ "' — re-run tools/build-travel-distances.mjs",
					travel.origins().contains(name));
			}
		}
		for (String name : SPELLS)
		{
			assertTrue("no travel field for spell '" + name + "'", travel.origins().contains(name));
		}
		for (String name : TREES)
		{
			assertTrue("no travel field for '" + name + "'", travel.origins().contains(name));
		}
		assertTrue("no travel field for the free home teleport",
			travel.origins().contains("Home Teleport"));
	}

	/**
	 * The case the whole thing was built for. Keep Le Faye is closer to
	 * Burthorpe than to the Fishing Trawler landing in a straight line, and
	 * further once White Wolf Mountain is in the way.
	 */
	@Test
	public void aMountainCostsMoreThanTheStraightLineSays()
	{
		TravelDistances travel = new TravelDistances();
		WorldPoint keepLeFaye = new WorldPoint(2757, 3401, 0);
		int burthorpe = travel.distance("Burthorpe Games Room", keepLeFaye);
		int trawler = travel.distance("Fishing Trawler", keepLeFaye);
		assertTrue("Burthorpe unknown", burthorpe > 0);
		assertTrue("Fishing Trawler unknown", trawler > 0);
		assertTrue("walking from Burthorpe (" + burthorpe + ") should cost more than"
			+ " from the Fishing Trawler (" + trawler + ") despite being nearer in a"
			+ " straight line", burthorpe > trawler);
	}

	/** Distances have to be plausible, not just present. */
	@Test
	public void knownShortWalksReadShort()
	{
		TravelDistances travel = new TravelDistances();
		int seers = travel.distance("Camelot Teleport", new WorldPoint(2725, 3491, 0));
		assertTrue("Camelot teleport to Seers' bank read " + seers + " tiles",
			seers > 0 && seers < 60);
		int falador = travel.distance("Falador Teleport", new WorldPoint(3013, 3355, 0));
		assertTrue("Falador teleport to the east bank read " + falador + " tiles",
			falador > 0 && falador < 150);
	}

	/**
	 * A landing with no ungated route to the mainland must say so rather than
	 * guess. Mos Le'Harmless is behind Cabin Fever; answering UNKNOWN is what
	 * keeps it out of the ranking instead of winning on a straight line drawn
	 * across the sea.
	 */
	@Test
	public void gatedRegionsAnswerUnknown()
	{
		TravelDistances travel = new TravelDistances();
		assertEquals("Trouble Brewing should have no ungated route to Varrock",
			TravelDistances.UNKNOWN,
			travel.distance("Trouble Brewing", new WorldPoint(3213, 3424, 0)));
	}
}
